//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class ReportUser
    {
        [DataMember]
        public int AccuserID { get; set; }
        [DataMember]
        public int OffenderID { get; set; }
        [DataMember]
        public string Description { get; set; }
        [DataMember]
        public int ID { get; set; }
    
        [IgnoreDataMember]
        public virtual Profile Profile { get; set; }
        [IgnoreDataMember]
        public virtual Profile Profile1 { get; set; }
    }
}
